#!/usr/bin/env python
import sys, os

components = ['gtest', '..']
recurse    = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    opt.load('g++')
    opt.load('boost')
    recurse(opt)

def configure(cfg):
    cfg.load('g++')
    cfg.load('boost')
    recurse(cfg)

    cfg.check_boost(
            lib='system',
            uselib_store='BOOST')

def build(bld):
    recurse(bld)

    bld(
        target          = 'main',
        features        = 'cxx cxxprogram',
        source          = bld.path.ant_glob('*.cc'),
        use             = ['pythonic', 'gtest', 'BOOST'],
        install_path    = 'bin',
        cxxflags        = [
                '-g',
                '-O0',
                '-std=c++0x',
                '-Wall',
                '-Wextra',
                '-pedantic',
            ],
        includes       = '.',
    )
